name: planting-grass

# [í¬ë¡ ìŠ¤ì¼€ì¥´ëŸ¬]
on:
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 1) Test 
        run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: 2) Exectue test
        run: echo "Test commit" >> notepad.txt && cat notepad.txt
      
