name: planting-grass

# [í¬ë¡ ìŠ¤ì¼€ì¥´ëŸ¬]
on:
  schedule:
    - cron: '*/1'
    
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
